# Spring Properties
spring:
  application:
     name: message-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# HTTP Server
server:
  port: 4444   # HTTP (Tomcat) port