/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rr225300' at '9/26/16 1:07 PM' with Gradle 2.12
 *
 * @author rr225300, @date 9/26/16 1:07 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
